baseURL = 'https://pueblaActiva.netlify.app/'
languageCode = "es"
title = "PueblaActiva"
theme = "pueblaActiva-1"


[params]
css = ["css/aos.css", "css/bootstrap.min.css", "css/font-awesome.min.css", "css/tooplate-gymso-style.css"]
